# Generated by Django 5.1.4 on 2024-12-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptarith', '0003_alter_question_user_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
